namespace Unpaint
{
  [default_interface]
  runtimeclass SettingControl : Windows.UI.Xaml.Controls.ContentControl
  {
    SettingControl();

    String Icon;
    static Windows.UI.Xaml.DependencyProperty IconProperty{ get; };

    String Title;
    static Windows.UI.Xaml.DependencyProperty TitleProperty{ get; };

    String Subtitle;
    static Windows.UI.Xaml.DependencyProperty SubtitleProperty{ get; };
  }

  [default_interface]
  runtimeclass MaskEditor : Windows.UI.Xaml.Controls.ContentControl, Windows.UI.Xaml.Data.INotifyPropertyChanged
  {
    MaskEditor();

    Windows.Graphics.Imaging.BitmapSize MaskResolution;
    static Windows.UI.Xaml.DependencyProperty MaskResolutionProperty{ get; };

    Double BrushSize;
    Double BrushEdge;
    Double BrushOpacity;

    Boolean IsBrushSelected{ get; };
    Boolean IsEraserSelected{ get; };

    void SelectBrush();
    void SelectEraser();

    void ClearMask();

    Boolean IsUndoAvailable{ get; };
    void UndoAction();

    Boolean IsRedoAvailable{ get; };
    void RedoAction();
  }
}
