namespace Unpaint
{
  runtimeclass SizeToStringConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    SizeToStringConverter();
  };

  runtimeclass IsNanToBooleanConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    IsNanToBooleanConverter();
  };

  runtimeclass NanToZeroConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    NanToZeroConverter();
  };

  runtimeclass StringToImageSourceConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    StringToImageSourceConverter();
  };
}