namespace Unpaint
{
  runtimeclass SizeToStringConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    SizeToStringConverter();
  };

  runtimeclass IsNanToBooleanConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    IsNanToBooleanConverter();
  };

  runtimeclass NanToZeroConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    NanToZeroConverter();
  };

  runtimeclass StringToImageSourceConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    StringToImageSourceConverter();
  };

  runtimeclass StorageFileToImageSourceConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    StorageFileToImageSourceConverter();
  };

  runtimeclass BooleanInverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    BooleanInverter();
  };

  runtimeclass EqualsConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    Boolean IsNegating;
    Object Value;

    EqualsConverter();
  };

  runtimeclass BooleanToGridLengthConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    BooleanToGridLengthConverter();

    Windows.UI.Xaml.GridLength TrueValue;
    Windows.UI.Xaml.GridLength FalseValue;
  }

  runtimeclass BooleanSwitchConverter : [default] Windows.UI.Xaml.Data.IValueConverter
  {
    BooleanSwitchConverter();

    Object TrueValue;
    Object FalseValue;
  }
}