import "ViewModels.idl";

namespace Unpaint
{
  [default_interface]
  runtimeclass DownloadModelDialog : Windows.UI.Xaml.Controls.ContentDialog
  {
    DownloadModelDialog();

    DownloadModelViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass ImportHuggingFaceModelDialog : Windows.UI.Xaml.Controls.ContentDialog
  {
    ImportHuggingFaceModelDialog();

    ImportHuggingFaceModelViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass ImportLocalModelDialog : Windows.UI.Xaml.Controls.ContentDialog
  {
    ImportLocalModelDialog();

    ImportLocalModelViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass ControlNetModelsDialog : Windows.UI.Xaml.Controls.ContentDialog
  {
    ControlNetModelsDialog();

    ControlNetModelsViewModel ViewModel{ get; };
  }
}
