namespace Unpaint
{
  struct ModelViewModel
  {
    String Id;
    String Uri;
  };

  [default_interface]
  runtimeclass ModelsViewModel
  {
    ModelsViewModel();

    IObservableVector<ModelViewModel> AvailableModels{ get; };
    IObservableVector<ModelViewModel> InstalledModels{ get; };
  }
}