import "ViewModels.idl";

namespace Unpaint
{
  [default_interface]
  runtimeclass MainView : Windows.UI.Xaml.Controls.Page, INavigationService
  {
    MainView();
  }

  [default_interface]
  runtimeclass WelcomeView : Windows.UI.Xaml.Controls.Page
  {
    WelcomeView();
  }

  [default_interface]
  runtimeclass ModelsView : Windows.UI.Xaml.Controls.Page
  {
    ModelsView();
    ModelsViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass InferenceView : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
  {
    InferenceView();
    InferenceViewModel ViewModel{ get; };

    Boolean IsStatusVisible{ get; };
    void ToggleSettingsLock();

    Boolean IsInputPaneVisible{ get; };
    void ToggleInputPane();
  }

  [default_interface]
  runtimeclass SettingsView : Windows.UI.Xaml.Controls.Page
  {
    SettingsView();
    SettingsViewModel ViewModel{ get; };
  }
}