import "ViewModels.idl";

namespace Unpaint
{
  [default_interface]
  runtimeclass ShowcaseView : Windows.UI.Xaml.Controls.Page
  {
    ShowcaseView();

    ShowcaseViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass WelcomeView : Windows.UI.Xaml.Controls.Page
  {
    WelcomeView();
  }

  [default_interface]
  runtimeclass ModelsView : Windows.UI.Xaml.Controls.Page
  {
    ModelsView();
    ModelsViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass InferenceView : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
  {
    InferenceView();
    InferenceViewModel ViewModel{ get; };

    Boolean IsStatusVisible{ get; };
    void ToggleSettingsLock();
    void ToggleJumpingToLatestImage();

    Boolean IsInputPaneVisible{ get; };
    void ToggleInputPane();
    
    void PasteFromClipboard();
  }

  [default_interface]
  runtimeclass SettingsView : Windows.UI.Xaml.Controls.Page
  {
    SettingsView();
    SettingsViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass InferenceOptionsView : Windows.UI.Xaml.Controls.UserControl
  {
    InferenceOptionsView();
    InferenceOptionsViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass PromptEditorView : Windows.UI.Xaml.Controls.UserControl
  {
    PromptEditorView();
    PromptEditorViewModel ViewModel{ get; };
  }

  [default_interface]
  runtimeclass ControlNetOptionsView : Windows.UI.Xaml.Controls.UserControl
  {
    ControlNetOptionsView();

    ControlNetOptionsViewModel ViewModel{ get; };
  }
}